### ISSUE TITLE
[BUG] Winning game causes bug

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#121]
Når spillet vinnes kommer følgende feilmelding: 
(Dette skjer ikke manuelt ved tastetrykk, men automatisk. Foreløpig skjer dette i "game.incrementRobotID()" (bør bli egen metode))

```Java
Checking if any robots have currently arrived at their next flag position...
updated flag visited
Congratulations you have collected all the flags, press 'W' to win the game.
A flag has been visited

Checking if someone won...
yeah2
yeah2
yeah2
yeah2
yeah2
yeah2
yeah2
yeah2
Found winner: true
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at roborally.game.Game.robotPlayNextCard(Game.java:282)
	at roborally.ui.gdx.events.Events.waitMoveEvent(Events.java:68)
	at roborally.ui.gdx.UI.render(UI.java:97)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

Process finished with exit code 0
```

**Comment by buzzdead** [comment]
Fixed in latest push.
