### ISSUE TITLE
[BUG] Register class

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#150]
Ref: #144 #149 

Får feilmeldinger når minst en av `Robot`ene har mindre enn **5 hp**.

- [x] Fiks Test 1
- ~~Fiks Test 2~~ #152
- [x] Fiks Test 3
- [x] Fiks Test 4

# For å reprodusere feilene
## Test 1
1. Få din `Robot` til å bare ha **5 eller mindre  hp**
2. Prøv å spill ved <kbd>ENTER</kbd>
    - Man kan ikke trykke **DONE** etter å ha valgt kort, siden man ikke velger nok kort i henhold til reglene.
    - Spillet vil krasje.

## ~~Test 2~~
1. ~~Få en vilkårlig `Robot` til å ha **5 eller mindre  hp**~~
2. ~~Prøv å starte en runde ved <kbd>ENTER</kbd>~~
    - ~~Spillet vil krasje. -> Feilmelding `Number of cards do not match number of available slots in registers`~~

## Test 3 #144
*NB! Denne er på en måte fikset i 7ea1350e5b40c7c9e28bab2dc1649c1fe0681aca*
1. Dytt en vilkårlig `Robot` utenfor brettet
2. Trykk <kbd>ENTER</kbd>
    - Spillet vil krasje

## Test 4
1. Når en `Robot` er fullstending ødelagt (alle reboots brukt opp)
2. Spillet krasjer. Se feilmelding under.

#### Test 1
```java
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at roborally.game.cards.CardsInHand.arrangeCards(CardsInHand.java:15)
	at roborally.game.gameboard.objects.robot.RobotLogic.arrangeCardsInHand(RobotLogic.java:135)
	at roborally.game.Game.shuffleTheRobotsCards(Game.java:195)
	at roborally.ui.gdx.events.AnimateEvent.drawCards(AnimateEvent.java:80)
	at roborally.ui.gdx.events.AnimateEvent.drawEvents(AnimateEvent.java:34)
	at roborally.ui.UI.render(UI.java:112)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Test 2
```java
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Number of cards do not match number of available slots in registers
	at roborally.game.cards.Register.add(Register.java:46)
	at roborally.game.gameboard.objects.robot.RobotLogic.fillFirstCardsFromHandIntoRegister(RobotLogic.java:197)
	at roborally.game.gameboard.objects.robot.RobotLogic.autoArrangeCardsInHand(RobotLogic.java:180)
	at roborally.game.Game.dealCards(Game.java:177)
	at roborally.ui.UI.keyUp(UI.java:153)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:325)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

### Test 4
```java
Blue -1
Locked cards: 0
In hand: 0
To place: 0
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Number of cards do not match number of available slots in registers
	at roborally.game.cards.Register.add(Register.java:42)
	at roborally.game.gameboard.objects.robot.RobotLogic.fillFirstCardsFromHandIntoRegister(RobotLogic.java:197)
	at roborally.game.gameboard.objects.robot.RobotLogic.autoArrangeCardsInHand(RobotLogic.java:180)
	at roborally.game.Game.dealCards(Game.java:177)
	at roborally.ui.UI.keyUp(UI.java:153)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:325)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by thomashusebo** [comment]
Noen spørsmål og kommentarer:
- Når man trykker 'T', så kjører IKKE en full runde. Ingen logik mtp kort blir kjørt
- Jeg mistenker at feilene kommer fordi robotene tar skade før de får kort. (man skubbe dem utenfor mappet/skyter/trykker 'T' i stedenfor å kjøre en vanlig runde)

Forslag til fix: 
- Enten fiks 'T' slik at en ORDENTELIG runde blir kjørt. i.e. alle får tildelt kort i registeret.
- Eller gi alle roboter random kort i registeret før spillet starter

**Comment by adipid** [comment]
> Spørsmål:
>1. Er testene gjort slik som nevnt av meg over,da burde fix nevnt under fungere
>2. Eller har du trykket ENTER for å velge kort, hver gang for å få roboter til å bevege seg? (altså en hel korrekt runde blir kjørt?). I såfall da er det nok noe annet som er galt

Begge deler er blitt gjort, både når jeg tester manuelt (ved bruk av piltastene osv) og når jeg prøver å spille spillet ordentlig.

Det er litt vanskelig å reprodusere feilene ved å spille spille ordentlig mtp at robotene gjør bare masse random og faller utenfor kartet hele tiden, og går tom for reboots. Dette gjør det svært tungvindt å teste, siden man mest sannsynlig nå restarte spillet for å kunne reprodusere feilene.
