### ISSUE TITLE
[BUG] Debug controls not up to date with ProgramCardsView

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#251]
Når man bruker debug controls til å ta skade så fungerer ikke programcardsview slik som det skal. I stedet for å få opp antall kort man har å velge sammen med de manglende kortene fra det som er låst i registeret så får man kun opp de kortene man har å velge mellom. Videre kaller man på nextCard i registeret med kort som er null og spillet avsluttes.

**Comment by adipid** [comment]
Kanskje lurt å refere til hvilke manuelle tester det gjelder?

**Comment by thomashusebo** [comment]
Ble funnet i forbindelse med [manuell tester for utdelte kort](https://github.com/inf112-v20/crawling-crow/wiki/Tester#22-antall-utdelte-kort)
1. Sett Debug Mode til true
2. Skad robot slik at noen kort blir låst, ved å bruke lasere. Se [Debug Mode](../wiki/Debug_Mode)
3. Sørg for at cleanup kjører. Se [Debug Mode](../wiki/Debug_Mode)
4. Trykk <kdb>ENTER</kbd> for å dele ut kort
    - Legg merke til at låste kort ikke viser
5. Velg kort
6. Trykk godkjenn
    - Spillet crasher:

```java
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Argument for @NotNull parameter 'card' of roborally/gameview/ui/ProgramCardsView.addCard must not be null
	at roborally.gameview.ui.ProgramCardsView.$$$reportNull$$$0(ProgramCardsView.java)
	at roborally.gameview.ui.ProgramCardsView.addCard(ProgramCardsView.java)
	at roborally.game.Game.setRegisterCardsView(Game.java:183)
	at roborally.game.Game.orderTheUserRobotsCards(Game.java:191)
	at roborally.events.AnimateEvent.drawCardsInHand(AnimateEvent.java:172)
	at roborally.events.AnimateEvent.drawCardsInHandAndRegister(AnimateEvent.java:54)
	at roborally.events.AnimateEvent.drawEvents(AnimateEvent.java:43)
	at roborally.gameview.GameView.runGameStates(GameView.java:152)
	at roborally.gameview.GameView.render(GameView.java:121)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by adipid** [comment]
> 2. Skad robot slik at noen kort blir låst, ved å bruke lasere. Se Debug Mode

2. Hvis du tar skade med <kbd>SPACE</kbd>, til du har noen låste kort, så skjer det. Men hvis man bruker <kbd>T</kbd> og deretter bruker <kbd>C</kbd> (for å gjøre `cleanUp()`) så fungerer det fint...

**Comment by thomashusebo** [comment]
Oppdaterer testsiden på wiki om hvordan vi kan gjøre dette, og lukker saken
