### ISSUE TITLE
AssetManager - getRobots() bug

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#38]
Det er ingen sjekk for at roboter er generert når man prøver å kalle robot. Ender opp med denne feilen i stedet. Forslag: Sørg for at AssetManager håndterer 'getRobots()' med en feilmelding hvis det ikke er noen roboter

Denne feilmeldingen sier meg ikke at feilen er at roboter aldri ble konstruert i asset manager:

```error
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at roborally.ui.gameboard.UI.keyUp(UI.java:77)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:325)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

For å klargjøre, ønsker at denne feilen kommer allerede her:

```java
robots = AssetsManager.getRobots();
AssetsManager.makeRobots();
```

Korrekt kode er:
```java
AssetsManager.makeRobots();
robots = AssetsManager.getRobots();
```

**Comment by buzzdead** [comment]
Var kun ment for å konstruere roboter til å teste maps foreløpig, så tok ikke hensyn til at man kalte på metodene i feil rekkefølge. Man henter ikke noe man ikke har laget enda på en måte. Men godt poeng, det er viktig å ta hensyn til slike ting. Sette grenser for hva som er tillatt og ikke tillatt å gjøre slik at man ikke ender med error.
